# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: "pip"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine build wheel
        python -m pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
    
    - name: Build package
      run: python -m pip wheel --no-deps . -w dist
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::335509591822:role/GitHubPathRoboticsOrg
        role-session-name: PublishPythonPackage
    
    - name: AWS Login
      run: aws codeartifact login --tool twine --repository Python --domain path-robotics --domain-owner 335509591822 --region us-east-2
    
    - name: Upload
      run: twine upload -r codeartifact dist/*.whl
